site_name: PyHo 2024
site_author: Python Ho
site_url: https://github.com/hopythonusergroup/2024.PyHo.Conference
# repo_url: https://github.com/hopythonusergroup/2024.PyHo.Conference
repo_name: hopythonusergroup/2024.PyHo.Conference
extra_css:
  - css/extra.css
theme:
  name: simple-blog
  components:
    footer: true
    preview: false
    title: false
    # menu: false
  colors:
    primary: black
    title: blue
    background: aliceblue
  site_name_style: bold
  logo: image/logo.jpg
  favicon: image/favicon.ico
  # name: simple-blog
  # custom_dir: custom_theme/
# nav:
#   - Home: index.md
#   - About:
#     - about/about.md
#     - about/hnspolicy.md
#     - about/volunteer.md
#   - Attend: attend.md
#   - Schedule: schedule.md
#   - Sponsors:
#     - sponsors/sponsor-us.md
#     - sponsors/our-sponsors.md
plugins:
  - blog:
      format: ""
      text-align: "left"
      display-article-date: false
markdown_extensions:
  - attr_list
copyright: Copyright &copy; 2024 - PythonHo
